# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

# Run the build across the last three versions of Windows Server for backwards compatibility
strategy:
  matrix:
    windows2019:
      imageName: "windows-2019"
  maxParallel: 1

pool:
  vmImage: $(imageName)

steps:

# Run the VisualsBulkDownloadTool.ps1 script to make sure there are no errors
- task: PowerShell@2
  inputs:
    filePath: '$(Build.SourcesDirectory)\\Misc\\VisualsBulkDownloadTool.ps1'
    arguments: '-CertifiedOnly -MicrosoftOnly'

# Test to make sure that there is at least one pbiviz file that was downloaded
- task: PowerShell@2
  inputs:
    filePath: '$(Build.SourcesDirectory)\\Tests\\VisualsBulkDownloadToolTests.ps1'

# Run the Python setup script
- task: PowerShell@2
  inputs:
    filePath: '$(Build.SourcesDirectory)\\Python\\PythonSetup.ps1'
