# Build pipeline for Azure DevOps
# https://aka.ms/yaml

# trigger CI builds off of master commits
trigger:
- master

jobs:
  # The Windows 2019 and Windows 2016 builds
- job: ModernWindows

  # run the build against different versions of Windows to test backwards compatability
  strategy:
    matrix:
      win2019:
        imageName: "windows-2019"
      win2016:
        imageName: "vs2017-win2016"
    maxParallel: 1

  pool:
    vmImage: $(imageName)

  steps:

  # Run the Pester Unit Test framework
  - powershell: '$(Build.SourcesDirectory)\\Tests\\Invoke-PesterAzureDevOps.ps1'
    displayName: 'Run Pester Unit Test Framework'

  # Publish the Pester test results
  - task: PublishTestResults@2
    displayName: "Publish Test Results"
    inputs:
      testRunTitle: 'Test Results for Pester'
      buildPlatform: 'Windows'
      testRunner: 'NUnit'
      testResultsFiles: '$(Build.SourcesDirectory)\\Tests\\TEST-RESULTS.xml'
      failTaskOnFailedTests: true # required to fail build when tests fail

  # The legacy Windows 2012 R2 Build
- job: LegacyWindows

  pool:
    vmImage: 'vs2015-win2012r2'
  
  steps:

  # Run the VisualsBulkDownloadTool.ps1 script to make sure there are no errors
  - task: PowerShell@2
    inputs:
      filePath: '$(Build.SourcesDirectory)\\Misc\\VisualsBulkDownloadTool.ps1'
      arguments: '-CertifiedOnly -MicrosoftOnly'

  # Test to make sure that there is at least one pbiviz file that was downloaded
  - task: PowerShell@2
    inputs:
      filePath: '$(Build.SourcesDirectory)\\Tests\\LegacyWin2012R2Tests.ps1'

  # Run the Python setup script
  - task: PowerShell@2
    inputs:
      filePath: '$(Build.SourcesDirectory)\\Python\\PythonSetup.ps1'