# Build pipeline for Azure DevOps
# https://aka.ms/yaml

# trigger CI builds off of master commits
trigger:
- master

# run the build against different versions of Windows to test backwards compatability
strategy:
  matrix:
    win2019:
      imageName: "windows-2019"
    win2016:
      imageName: "vs2017-win2016"
  maxParallel: 1

pool:
  vmImage: $(imageName)

steps:

# Run the Pester Unit Test framework
- powershell: '$(Build.SourcesDirectory)\\Tests\\Invoke-PesterAzureDevOps.ps1'
  displayName: 'Run Pester Unit Test Framework'

# Publish the Pester test results
- task: PublishTestResults@2
  displayName: "Publish Test Results"
  inputs:
    testRunTitle: 'Test Results for Pester'
    buildPlatform: 'Windows'
    testRunner: 'NUnit'
    testResultsFiles: '$(Build.SourcesDirectory)\\Tests\\TEST-RESULTS.xml'
    failTaskOnFailedTests: true # required to fail build when tests fail