# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:

# Run the VisualsBulkDownloadTool.ps1 script to make sure there are no errors
- task: PowerShell@2
  displayName: "Running VisualsBulkDownloadTool.ps1 script"
  inputs:
    filePath: '$(Build.SourcesDirectory)\\Misc\\VisualsBulkDownloadTool.ps1'
    arguments: '-CertifiedOnly -MicrosoftOnly'

# Test to make sure that there is at least one pbiviz file that was downloaded
- task: PowerShell@2
  displayName: "Running tests agains the results of VisualsBulkDownloadTool.ps1 script running"
  inputs:
    filePath: '$(Build.SourcesDirectory)\\Tests\\VisualsBulkDownloadToolTests.ps1'

# Run the Python setup script
- task: PowerShell@2
  displayName: "Running python setup script to install modules required for Power BI"
  inputs:
    filePath: '$(Build.SourcesDirectory)\\Python\\PythonSetup.ps1'