# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:

# Run the VisualsBulkDownloadTool.ps1 script to make sure there are no errors
- task: PowerShell@2
  inputs:
    filePath: '$(Build.SourcesDirectory)\\Misc\\VisualsBulkDownloadTool.ps1'

# Test to make sure at least one pbiviz file was downloaded
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '# check in the downloads folder to see if at least one pbiviz file was downloaded
      $pbiVizFileCount = (Get-ChildItem -Path $(Build.SourcesDirectory)\\Misc\\downloads -Filter *.pbiviz -Recurse).Count
      $pbiVizFilesExist = $pbiVizFileCount -gt 0
      
      Write-Output "Found $pbiVizFileCount pbiviz files in the downloads folder"

      # if the folder does not contain a pbiviz file, throw an exception
      if(-not $pbiVizFilesExist){ throw "No pbiviz files were downloaded" }'